# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'

  # custom commands to run mkdocs build within hatch, as suggested by maintainer in
  # https://github.com/readthedocs/readthedocs.org/issues/10706
  commands:
    - pip install hatch
    - hatch run docs:build
    - mkdir --parents $READTHEDOCS_OUTPUT
    - mv site $READTHEDOCS_OUTPUT/html
